### ISSUE TITLE
cannot clone due to 'examples/ansible-files/files/apache-artifact-2021-12-03T13:57:46.346551+00:00.json'

### ISSUE THREAD

**Issue by MichalZonis** [rhmk/ansible-cli-container#2]
I tried to clone the repo in order to follow a course, but it failed with the following error 
$ git clone https://github.com/rhmk/ansible-cli-container.git
Cloning into 'ansible-cli-container'...
remote: Enumerating objects: 117, done.
remote: Counting objects: 100% (117/117), done.
remote: Compressing objects: 100% (77/77), done.
remote: Total 117 (delta 38), reused 87 (delta 19), pack-reused 0Receiving objecReceiving objects:  85% (100/117)
Receiving objects: 100% (117/117), 26.56 KiB | 2.66 MiB/s, done.
Resolving deltas: 100% (38/38), done.
error: invalid path 'examples/ansible-files/files/apache-artifact-2021-12-03T13:57:46.346551+00:00.json'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by rhmk** [comment]
Thanks for leaving this comment. This is strange error I haven't seen so far. I will investigate further and let you ASAP

**Comment by rhmk** [comment]
where did you run this command? I can't reproduce your issue neither on Mac nor on Linux. It seems that you either try to checkout in a non-empty directory that contains examples/ansible-files/files/apache-artifact-2021-12-03T13:57:46.346551+00:00.json or the OS you are using has difficulties with the filename format, (colon or . in the filename)

**Comment by rhmk** [comment]
As a first step I would try to follow the git recommendations. To get the environment it should be sufficient to just run the container issuing the above podman commands mentioned in the Readme. There is no need to build the container yourself
It is also not really important to get this particular file, as it just an example output.

**Comment by MichalZonis** [comment]
After this I managed to clone and it just cloned without this particular file. I'm Not sure why but thank you anyway for your time.

**Comment by rhmk** [comment]
No worries. IDo you clone this on windows? If yes, I assume Windows has some trouble with the special characters in the filename(: or +)
